name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/checkout@v3
    - name: 'Cache node_modules'
      uses: actions/cache@v3
      with:
        path: '~/.npm'
        key: "ubuntu-latest-node-v16-${{ hashFiles('**/package-lock.json') }}"
        restore-keys: |
          ubuntu-latest-node-v16-
    - name: Install Packages
      run: npm install
    - name: Check linter
      run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/checkout@v3
    - name: Install Packages
      run: npm install
    - name: Check types
      run: npm run test:typecheck
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: actions/checkout@v3
    - name: Install Packages
      run: npm install
    - name: Check types
      run: npm run test
