name: Continuous integration

on:
  push:
  pull_request:

jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Packages
      run: npm install
    - name: Check lint
      run: npm run lint
      
  typecheck:
    name: Check typescript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Packages
      run: npm install
    - name: Check types
      run: npm run test:typecheck
      
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Packages
      run: npm install
    - name: Run tests
      run: npm run test
    - name: Collect coverage
      uses: coverallsapp/github-action@1.1.3

  node_os:
    name: Test in diff os and node version
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [19.x, 18.x, 17.x, 16.x, 14.x]
        #include:
        #- os: windows-latest
        #  node: "16.x"
        #- os: macOS-latest
        #  node: "16.x"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - name: Install Packages
      run: npm install
    - name: Run tests
      run: npm run test
